### ISSUE TITLE
Installation fails with python3.7 inside WSL

### ISSUE THREAD

**Issue by black-snow** [owtf/owtf#1003]
```bash
$ python3 --version
Python 3.7.0

$ python3 -m pip --version
pip 18.1 from /home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/pip (python 3.7)

$ python3 -m pip install --upgrade git+https://github.com/owtf/owtf#egg=owtf
...
 ext/_yaml.c:24217:11: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_traceback'
         tstate->exc_traceback = local_tb;
               ^
    error: command 'cc' failed with exit status 1

    ----------------------------------------
Command "/home/linuxbrew/.linuxbrew/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-rxzyud8i/pyyaml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-9y74spfs/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-rxzyud8i/pyyaml/
```

Is python3.7 not supported?

**Comment by viyatb** [comment]
I found a reference to a similar error at https://stackoverflow.com/questions/51165585/pip3-install-pyyaml-failed-python3-7-macos-high-sierra. You might also need `libyaml` (which provides Python bindings) to install `PyYaml` correctly.

**Comment by black-snow** [comment]
I manually pip installed pyyaml but the outcome is the same. I wonder why most packages still don't work with python 3.7 ... sure, it's still kinda new but not THAT new ...
I guess there ain't much that you could do except switching to another yaml lib that (the pypi package) runs fine on 3.7+

I'll fallback to a VM then, thanks.
